ARG AWS_ACCESS_KEY_ID
ARG AWS_S3_BUCKET
ARG AWS_SECRET_ACCESS_KEY
ARG DB_PASSWORD
ARG DB_URL
ARG DB_USERNAME
ARG MAIL_USERNAME
ARG MAIL_APP_PASSWORD
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_SECRET

FROM openjdk:17-jdk-slim

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_S3_BUCKET=${AWS_S3_BUCKET}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_APP_PASSWORD=${MAIL_APP_PASSWORD}
ENV KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
ENV KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}

COPY ./build/libs/coding_convention-0.0.1-SNAPSHOT.jar /app.jar

CMD ["java", "-jar", "app.jar"]